app/models.py
from database import db


class Course(db.Model):
    __tablename__ = 'course'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(100), nullable=False)
    author_id = db.Column(db.Integer, db.ForeignKey('author.id'), nullable=False)
    platform = db.Column(db.String(100))
    completion_date = db.Column(db.Date)
    
    author = db.relationship('Author', back_populates='courses')
    
    def __init__(self, name, author_id, platform, completion_date):
        self.name = name
        self.author_id = author_id
        self.platform = platform
        self.completion_date = completion_date
        
        
class Author(db.Model):
    __tablename__ = 'author'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(150), nullable=False)
    
    courses = db.relationship('Course', back_populates='author')
    
    def __init__(self, name):
        self.name = name
    

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, SelectField, SubmitField
from wtforms.validators import DataRequired

class CourseForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    author_name = StringField('Author', validators=[DataRequired()])
    platform = StringField('Platform')
    completion_date = DateField('Completion Date', format='%Y-%m-%d')
    submit = SubmitField('Add')
    
class AuthorForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])

app/app.py
from flask import Flask
from sqlalchemy.exc import ProgrammingError
from database import db
from config import ProductionConfig
from routes import blueprint
from schemas import ma
from os import environ,getenv


def create_app(config_name=None):
    app = Flask(__name__)

    if not config_name:
        env = environ.get("FLASK_ENV", "dev")
        if env == "prod":
            config_name = ProductionConfig()
        elif env == "test":
            config_name = TestingConfig()
        else:
            config_name = DevelopmentConfig()

    app.config.from_object(config_name)
    app.config['SECRET_KEY'] = getenv('SECRET_KEY')

    db.init_app(app)
    ma.init_app(app)

    app.register_blueprint(blueprint)

    with app.app_context():
        try:
            db.create_all()
        except ProgrammingError:
            print("Table exists")


    return app

if __name__ == "__main__":
    app = create_app()
    app.run(host='0.0.0.0')

app/routes.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for
from models import Course, Author
from schemas import CourseSchema, AuthorSchema
from forms import CourseForm, AuthorForm
import services
import socket


blueprint = Blueprint('api', __name__)


@blueprint.route('/health', methods=['GET'])
def health_check():
    return jsonify({ 'msg': 'OK'})  

@blueprint.route('/info', methods=['GET'])
def get_info():
    return jsonify(hostname=socket.gethostname())

@blueprint.route('/')
def home():
    return render_template('base.html')
    
@blueprint.route('/course', methods=['GET'])
def get_courses():
    courses = services.get_all_courses()
    return render_template('index.html', courses=courses)

@blueprint.route('/course', methods=['POST'])
def add_course():
    form = CourseForm()

    if form.validate_on_submit():
        name = form.name.data
        author_name = form.author_name.data
        platform = form.platform.data
        completion_date = form.completion_date.data
        
        services.create_course(name, author_name, platform, completion_date)
        return redirect(url_for('api.get_courses'))
    
    return render_template('manage_course.html', form=form)

@blueprint.route('/course/edit/<int:id>/', methods=['GET','POST','PATCH'])
def update_course(id):
    course = services.get_course_by_id(id)
    form = CourseForm(obj=course)
    
    if request.method == 'POST' and  request.form.get("_method") == "PATCH"  and form.validate_on_submit():
        name = form.name.data
        author_name = form.author_name.data
        platform = form.platform.data
        completion_date = form.completion_date.data
        
        services.update_course(name, author_name, platform, completion_date, id)
        return redirect(url_for('api.get_courses'))
    
    print(form.errors)
    return render_template('manage_course.html', form=form, edit=True, id=id)


@blueprint.route('/course/<int:id>/', methods=['POST'])
def delete_course(id):    
    if request.form.get("_method") == "DELETE":
        services.delete_course(id)
        return redirect(url_for('api.get_courses'))


@blueprint.route('/author', methods=['GET'])
def get_authors():
    authors = services.get_all_authors()
    return render_template('authors.html', authors=authors)

@blueprint.route('/author', methods=['POST'])
def add_author():
    form = AuthorForm()
    name = form.name.data
    
    if form.validate_on_submit():
        services.create_author(name)
        return redirect(url_for('api.get_authors'))

    return render_template('manage_author.html', form=form, edit=False)

@blueprint.route('/author/edit/<int:id>/', methods=['GET', 'POST', 'PUT'])
def update_author(id):
    author = services.get_author_by_id(id)
    form = AuthorForm(obj=author)
    
    if request.method == 'POST' and request.form.get("_method") == "PUT"  and form.validate_on_submit():
        name = form.name.data
        services.update_author(name, id)
        return redirect(url_for('api.get_authors'))
        
    return render_template('manage_author.html', form=form, id=id, edit=True)


@blueprint.route('/author/<int:id>/', methods=['POST', 'DELETE'])
def delete_author(id):
    if request.method == 'POST' and request.form.get("_method") == "DELETE":
        services.delete_author(id)
        return redirect(url_for('api.get_authors'))

app/templates/authors.html
{% extends "base.html" %}

{% block title %}
    Course Authors
{% endblock %}

{% block content %}
<div class="container">
    <div class="row"></div>
        <div class="col-2"></div>
        <div class="col d-flex justify-content-center h1">Authors</div>
        <div class="col-2"></div>
        <HR>
    </div>
</div>

<div class="container mt-4">
    <div class="row">
        <div class="col d-flex justify-content-end">
            <form action="{{ url_for('api.add_author') }}" method="POST" style="display: inline;">
                <button type="submit" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Add Author
                </buton>
            </form>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row justify-content-center">
        <table class="table">
            <thead class="thead">
                <tr>
                    <th>Author</th>
                    <th>Courses</th>

                </tr>
            </thead>
            <tbody>
                {% for author in authors %}
                <tr>
                    <td>{{ author.name }}</td>
                    <td>{{ author.courses|join(', ') }}</td>
                    <td>
                        <a href="/author/edit/{{ author.id }}" class="action-btn edit">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                    
                        <form action="{{ url_for('api.delete_author', id=author.id)}}" method="POST" style="display:inline;">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="action-btn delete">
                                <i class="bi bi-trash"></i>
                            </button>
                        </form>
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Courses App - Application about completed courses{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for("static", filename="styles.css") }}">
  </head>
  <body>
    {% include "menu.html" %}
    {% block content %}
    <div class="container">
        <div class="row"></div>
            <div class="col-2"></div>
            <div class="col d-flex justify-content-center h1">My Completed Courses</div>
            <div class="col-2"></div>
            <HR>
        </div>
        <div class="row mt-5">
            <div class="col-2"></div>
            <div class="col d-flex justify-content-center p">Here you can find a courses I have completed. These courses helped me develop skills in areas like: programming and DevOps.</div>
            <div class="col-2"></div>
    </div>
    
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}
    Courses
{% endblock %}

{% block content %}
<div class="container">
    <div class="row"></div>
        <div class="col-2"></div>
        <div class="col d-flex justify-content-center h1">Completed Courses</div>
        <div class="col-2"></div>
        <HR>
    </div>
</div>

 <div class="container mt-4">
    <div class="row">
        <div class="col d-flex justify-content-end">
            <form action="{{ url_for('api.add_course') }}" method="POST" style="display: inline;">
                <button type="submit" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Add Course
                </buton>
            </form>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row justify-content-center">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Platform</th>
                    <th>Author</th>
                    <th>Completion Date</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                    <td>{{ course.name }}</td>
                    <td>{{ course.platform }}</td>
                    <td>{{ course.author_name }}</td>
                    <td>{{ course.completion_date }}</td>
                    <td>
                        <a href="/course/edit/{{ course.id }}" class="action-btn edit">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                        <form action="{{ url_for("api.delete_course", id=course.id) }}" method="POST" style="display:inline;">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="action-btn delete">
                                <i class="bi bi-trash"></i>
                            </button>
                        </form>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/manage_author.html
<form method="POST" action="{{ url_for('api.update_author', id=id) if edit else url_for('api.add_author') }}">
    {% if edit %}
        <!-- Ukryte pole dla metody PUT -->
        <input type="hidden" name="_method" value="PUT">
    {% endif %}

    <!-- CSRF Token -->
    {{ form.csrf_token }}

    <!-- Formularz -->
    <div class="form-group mb-3">
        <label for="author-name" class="form-label">{{ form.name.label }}</label>
        {{ form.name(class="form-control", id="author-name", placeholder="Enter author's name") }}
    </div>

    <!-- Przycisk wysyłania -->
    <div class="text-center">
        <button type="submit" class="btn btn-primary">
            {{ 'Edit' if edit else 'Add' }}
        </button>
    </div>
</form>

app/templates/manage_course.html
<form method="POST" action="{{ url_for('api.update_course', id=id) if edit else url_for('api.add_course') }}" class="needs-validation" novalidate>
    {% if edit %}
        <!-- Ukryte pole dla metody PATCH -->
        <input type="hidden" name="_method" value="PATCH">
    {% endif %}

    <!-- CSRF Token -->
    {{ form.csrf_token }}

    <!-- Nagłówek -->
    <h2 class="mb-4 text-center">{{ 'Edit Course' if edit else 'Add Course' }}</h2>

    <!-- Formularz z polami w jednej linii -->
    <div class="mb-3 d-flex align-items-center">
        <label for="course-name" class="form-label me-3" style="min-width: 150px;">{{ form.name.label }}</label>
        {{ form.name(class="form-control", id="course-name", placeholder="Enter course name", style="flex: 1;") }}
    </div>

    <div class="mb-3 d-flex align-items-center">
        <label for="author-name" class="form-label me-3" style="min-width: 150px;">{{ form.author_name.label }}</label>
        {{ form.author_name(class="form-control", id="author-name", placeholder="Enter author name", style="flex: 1;") }}
    </div>

    <div class="mb-3 d-flex align-items-center">
        <label for="platform" class="form-label me-3" style="min-width: 150px;">{{ form.platform.label }}</label>
        {{ form.platform(class="form-control", id="platform", placeholder="Enter platform name", style="flex: 1;") }}
    </div>

    <div class="mb-3 d-flex align-items-center">
        <label for="completion-date" class="form-label me-3" style="min-width: 150px;">{{ form.completion_date.label }}</label>
        {{ form.completion_date(class="form-control", id="completion-date", type="date", style="flex: 1;") }}
    </div>

    <!-- Przycisk wysyłania -->
    <div class="text-center">
        <button type="submit" class="btn btn-primary">
            {{ 'Edit' if edit else 'Add' }}
        </button>
    </div>
</form>

app/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/course">Courses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/author">Authors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">About Me</a>
                </li>
            </ul>
        </div>
    </div>
</nav>